### PR TITLE
Fix your example link

### PR DESCRIPTION
**Pull request by skvale**
The link was broken for the example to propTypes.  I found another example in https://github.com/Khan/react-select/blob/master/src/Option.js#L5 that should do the trick.

### CODE REVIEW

**Comment by csilvers** [comment]
Ah, interesting.  The link we have now is in a private repo, which is why you can't see it.  I like the example you found, but would love even more if we could find a more complex example that has shapeOf and arrays and the like.  Do you happen to know of any examples like that in some of the public KA (or otherwise!) repos?  If not, we'll go with the one you found in react-select.

**Comment by jlfwong** [comment]
Perhaps https://github.com/Khan/react-components/blob/master/js/button-group.jsx#L34?

**Comment by skvale** [comment]
@jlfwong Yes, like your choice better: [button-group](https://github.com/Khan/react-components/blob/777ef0aa8be86124467a22b5bfa660fe592e7033/button-group.jsx#L23)

@csilvers The [PropTypes](https://facebook.github.io/react/docs/reusable-components.html) link provided in the header does have arrayOf.  Maybe we could expand on what isn't there with an inline example for shapeOf and whichever other examples you wanted to include.

**Comment by csilvers** [comment]
ButtonGroup isn't awesome because it uses `any`, which the style guide recommends against.

We were hoping to avoid an inline example -- which could get quite large -- by pointing to an existing use.  But maybe there's not a perfect one around yet.

**Comment by csilvers** [comment]
Anyone on this thread know if a better example has popped up since we last discussed this?

**Pull request closed without merging**
