### PR TITLE
React update

### PR DESCRIPTION
**Pull request by csilvers**
Revamp the style guide formatting, rewrite it, and add a few rules.

### CODE REVIEW

**Comment by kevinbarabash** [comment]
We might also want to specify the order of methods.  We can lint for this using https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-comp.md which is quite configurable.

**Comment by dangoor** [comment]
These changes look good to me!

I thought we had left it that we were going to suggest the use of Redux but not get too specific about how to use it until we have more best practices in mind. Is that right?

**Comment by jaredly** [comment]
@kevinbarabash having a lint for this sounds super annoying :/ having to remember an ordering on >10 possible lifecycle methods?
That said, I'm all for saying in the style guide: first lifecycle, then custom (handlers etc.) then `render` last

**Comment by jaredly** [comment]
Oh wait, looks like you can do
```js

**Comment by xymostech** [comment]
@dangoor Use of Redux doesn't really belong in the Style guide, it's a best practice; this is more for specifics on how to use React itself.

**Comment by csilvers** [comment]
@kevinbarabash good idea I'll add a section on function ordering.

**Comment by csilvers** [comment]
@jaredly as the primary reviewer, are you ok with these changes? -- once comments have settled down, can I check this in?

**Comment by dangoor** [comment]
@xymostech Gotcha, thanks.

**Comment by csilvers** [comment]
@kevinbarabash @jaredly is there an ordering we should suggest for the lifecycle methods?  Like chronological order or something?  (Is there a strict chronological order for lifecycle methods?)

**Comment by kevinbarabash** [comment]
@csilvers I was thinking chronological order.  From https://facebook.github.io/react/docs/component-specs.html, it should be:
- getInitialState
- getDefaultProps
- componentWillMount
- componentDidMount
- componentWillReceiveProps
- shouldComponentUpdate
- componentWillUpdate
- componentDidUpdate
- componentWillUnmount

@jaredly am I missing anything?

**Comment by spicyj** [comment]
getDefaultProps gets called first (and only once).

**Comment by xymostech** [comment]
@csilvers this should be closed now, correct?

**Comment by csilvers** [comment]
Committed in 8659322c5d782d352a3e5b0644ac851e4904ec95

**Pull request closed without merging**
